root: true

plugins:
  - prettier

parserOptions:
  ecmaVersion: 12
  parser: "@typescript-eslint/parser"
  sourceType: module

extends:
  - plugin:vue/vue3-recommended
  - plugin:prettier/recommended

rules:
  prettier/prettier: error
  vue/multi-word-component-names: off
